version: "3.7"

services:
  web:
    build: .
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/manage_books
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_MULTIPLE_DATABASES="${POSTGRES_DB}","${TEST_POSTGRES_DB}"
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
volumes:
  postgres_data: