"""Rename hash_password tp password in user model

Revision ID: 37ec80319b20
Revises: 7db28b5fb330
Create Date: 2022-09-29 18:10:09.331640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "37ec80319b20"
down_revision = "7db28b5fb330"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(), nullable=False))
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "password")
    # ### end Alembic commands ###
